import { Translations } from "./langTypes";

export const enTranslations: Translations = {
  titles: {
    services: "Services",
    values: "Values",
    process: "Process",
    features: "Features",
    inspired: "Inspired",
    history: "History",
    work: "My Work",
    contact: "Contact",
    reviews: "Reviews",
    blog: "Blog",
  },
  buttons: {
    workWithMe: "Work with me",
    view: "View",
    contact: "Contact",
    send: "Send",
  },
  form: {
    name: "Name*",
    email: "Email*",
    companyName: "Company Name",
    budget: "Budget",
    message: "Message*",
    sent: "Email Was Sent",
  },
  nav: {
    home: "Home",
    services: "Services",
    tattoo: "Tattoo",
    henna: "Henna",
    blog: "Blog",
    contact: "Appointment",
    portfolio: "Portfolio",
    courses: "Courses",
    inPerson: "In Person",
    online: "Online",
    flash: "Flash",
    canvases: "Canvases",
    boutique: "Boutique",
    testTattoo: "Test Tattoo",
  },
  other: {
    reserve: "Reserve",
  },
  select: {
    sort: "Sort",
    filter: "Filter",
    dateSort: {
      newest: "Newest",
      oldest: "Oldest",
    },
    year: "Year",
    bodyParts: "Body Parts",
    bodyPartsOptions: {
      hand: "Hand",
      arm: "Arm",
      foot: "Foot",
      leg: "Leg",
      back: "Back",
      chest: "Chest",
      face: "Face",
    },
    flashStyles: "Style",
    flashStylesOptions: {
      animal: "Animal",
      character: "Character",
      floral: "Floral",
      mandala: "Mandala",
      ornamental: "Ornamental",
      other: "Other",
    },
    flashStatus: "Status",
    flashStatusOptions: {
      reserved: "Reserved",
      unReserved: "Unreserved",
    },
    hennaColors: "Color",
    hennaColorsOptions: {
      henna: "Henna",
      hennagua: "Hennagua",
      jagua: "Jagua",
    },
  },
};
