import { Translations } from "./langTypes";

export const enTranslations: Translations = {
  titles: {
    history: "History",
    work: "My Work",
    reviews: "Reviews",
    blog: "Blog",
    tarif: "Tarif",
    info: "Information",
    experience: "Live the Experience",
    cart: "Cart",
  },
  buttons: {
    view: "View",
    addToCart: "Add to cart",
    submit: "Submit",
  },
  form: {
    general: {
      firstName: "First Name",
      firstNamePlaceholder: "Joe",
      lastName: "Last Name",
      lastNamePlaceholder: "Smith",
      email: "Email",
      emailPlaceholder: "example@example.com",
      requiredAlert: "Fill out all required fields",
      emailSent: "Email sent successfully",
      emailNotSent: "Email not sent",
      availabilities: "Availabilities",
      availabilitiesPlaceholder: "Every Tuesday and...",
      additionalInfo: "Additional Information",
      info: "Pertinent Information",
      infoPlaceholder: "Description of the project",
      referanceImage: "Referance Image",
      upload: "Upload Image",
    },
    cart: {
      province: "Province",
      city: "City",
      postalCode: "Postal Code",
      postalCodePlaceholder: "A1A 1A1",
      delivery: "Delivery method",
      addressLine: "Address Line",
    },
    flash: {
      bodyPosition: "Body Position",
      bodyPositionPlaceholder: "I would like one along my leg...",
      selectedFlash: "Selected Flash",
    },
    contact: {
      service: "Service",
      plan: "Plan",
      size: "Size",
      length: "Lenght",
      width: "Width",
      unit: "inches",
    },
  },
  nav: {
    home: "Home",
    services: "Services",
    tattoo: "Tattoo",
    testTattoo: "Test Tattoo",
    henna: "Henna",
    courses: "Courses",
    inPerson: "In Person",
    online: "Online",
    portfolio: "Portfolio",
    flash: "Flash",
    toiles: "Canvases",
    boutique: "Boutique",
    blog: "Blog",
    contact: "Appointment",
    cart: "Cart",
    privacy: "Privacy Policy",
    terms: "Terms and Conditions",

    other: "Other",
  },
  hours: {
    title: "Opening Hours",
    to: "to",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
  },
  other: {
    reserve: "Reserve",
  },
  cart: {
    itemsAddedToCart: "items have been added to cart",
    itemAddedToCart: "item has been added to cart",
    checkCartAlert: "Check Cart",
    total: "Total",
    noItemsInCart: "No items in cart. Please check Boutique",
  },
  select: {
    sort: "Sort",
    filter: "Filter",
    select: "Select an Option",
    dateSort: {
      newest: "Newest",
      oldest: "Oldest",
    },
    year: "Year",
    bodyParts: "Body Parts",
    bodyPartsOptions: {
      hand: "Hand",
      arm: "Arm",
      foot: "Foot",
      leg: "Leg",
      back: "Back",
      chest: "Chest",
      face: "Face",
    },
    tattooColor: "Color",
    tattooColorOptions: {
      black: "Black + Grey",
      brown: "Brown",
    },
    tattooStatus: "Status",
    tattooStatusOptions: {
      healed: "Healed",
    },
    flashStyles: "Style",
    flashStylesOptions: {
      animal: "Animal",
      character: "Character",
      floral: "Floral",
      mandala: "Mandala",
      ornamental: "Ornamental",
      other: "Other",
    },
    flashStatus: "Status",
    flashStatusOptions: {
      reserved: "Reserved",
      unReserved: "Unreserved",
      repeatable: "Repeatable",
    },
    hennaColors: "Color",
    hennaColorsOptions: {
      henna: "Henna",
      hennagua: "Hennagua",
      jagua: "Jagua",
    },
  },
};
