import { Translations } from "./langTypes";

export const frTranslations: Translations = {
  titles: {
    history: "Histoire",
    work: "Mon Travail",
    reviews: "Avis",
    blog: "Blog",
    tarif: "Tarif",
    info: "Information",
    experience: "Vivre l'expérience",
    cart: "Panier",
    policies: "Politiques",
  },
  buttons: {
    view: "Voir",
    addToCart: "Ajouter au panier",
    submit: "Soumettre",
  },
  form: {
    general: {
      firstName: "Prénom",
      firstNamePlaceholder: "Joe",
      lastName: "Nom de famille",
      lastNamePlaceholder: "Smith",
      email: "Email",
      emailPlaceholder: "exemple@exemple.com",
      requiredAlert: "Veuillez remplir tous les champs obligatoires",
      emailSent: "Email envoyé avec succès",
      emailNotSent: "Email non envoyé",
      availabilities: "Disponibilités",
      availabilitiesPlaceholder: "Tous les mardis et...",
      additionalInfo: "Informations supplémentaires",
      info: "Informations pertinentes",
      infoPlaceholder: "Description du projet",
      referanceImage: "Image de référence",
      upload: "Télécharger des images",
    },
    cart: {
      province: "Province",
      city: "Ville",
      postalCode: "Code postal",
      postalCodePlaceholder: "A1A 1A1",
      delivery: "Méthode de livraison",
      addressLine: "Adresse",
    },
    flash: {
      bodyPosition: "Position du corps",
      bodyPositionPlaceholder: "Je voudrais une le long de ma jambe...",
      selectedFlash: "Flash sélectionné",
    },
    contact: {
      service: "Service",
      plan: "Plan",
      size: "Taille",
      length: "Longueur",
      width: "Largeur",
      unit: "Pouces",
    },
  },

  nav: {
    home: "Accueil",
    services: "Services",
    tattoo: "Tattoo",
    henna: "Henna",
    testTattoo: "Test Tatouage",
    courses: "Cours",
    online: "En ligne",
    inPerson: "En personne",
    portfolio: "Portfolio",
    flash: "Flash",
    toiles: "Toiles",
    boutique: "Boutique",
    contact: "Rendez-vous",
    blog: "Blog",
    cart: "Panier",
    privacy: "Politique de confidentialité",
    policies: "Politiques",
    terms: "Conditions d'utilisation",
    other: "Autre",
  },
  hours: {
    title: "Heures d’ouverture",
    to: "à",
    monday: "Lundi",
    tuesday: "Mardi",
    wednesday: "Mercredi",
    thursday: "Jeudi",
    friday: "Vendredi",
    saturday: "Samedi",
    sunday: "Dimanche",
  },
  other: {
    reserve: "Réserver",
    repeatable: "Répétable",
    notAvailable: "Non disponible",
  },
  cart: {
    itemsAddedToCart: "articles ont été ajoutés au panier",
    itemAddedToCart: "article ajoute au panier",
    checkCartAlert: "Voir le Panier",
    noItemsInCart: "Panier vide. Ajoutez des articles pour continuer",
    total: "Total",
  },
  select: {
    sort: "Trier",
    filter: "Filtrer",
    select: "Sélectionner une option",
    dateSort: {
      newest: "Récent",
      oldest: "Ancien",
    },

    year: "Anne",
    bodyParts: "Parties du Corps",
    bodyPartsOptions: {
      hand: "Main",
      arm: "Bras",
      foot: "Pied",
      leg: "Jambe",
      back: "Dos",
      chest: "Poitrine",
      face: "Visage",
    },
    tattooColor: "Couleur",
    tattooColorOptions: {
      black: "Noir + Gris",
      brown: "Brun",
    },
    tattooOther: "Autre",
    tattooOtherOptions: {
      healed: "Guéri",
      "cover-up": "Cover-up",
    },
    flashStyles: "Styles",
    flashStylesOptions: {
      ornamental: "Ornamental",
      floral: "Floral",
      mandala: "Mandala",
      animal: "Animal",
      character: "Personnage",
      other: "Autre",
    },
    flashStatus: "Statut",
    flashStatusOptions: {
      reserved: "Réservé",
      unReserved: "Non Réservé",
      repeatable: "Répétable",
    },
    hennaColors: "Couleurs",
    hennaColorsOptions: {
      henna: "Henné",
      hennagua: "Hennagua",
      jagua: "Jagua",
    },
    articleType: "Type",
    articleTypeOptions: {
      tattoo: "Tatouage",
      henna: "Henné",
      jagua: "Jagua",
      toile: "Toile",
    },
  },
};
